spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FamilyMedicalRecords?useSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  graphql:
    schema:
      locations: classpath:graphql/

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1074471028840-iod6ivlk98j1p0htpnqs8283re84enas.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          facebook:
            client-id: 2220741931733563
            client-secret: dc1f0e8267656c037ea510e31b7867e6
            scope: public_profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v14.0/dialog/oauth
            token-uri: https://graph.facebook.com/v14.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id

server:
  port: 8080

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret:
    key: ${JWT_SECRET_KEY:SjkwTjN5aG41V2t6M0p4SllYNDlRYzJmQnU4cTgyMXFhU1hIUlJjS00=}
  expiration:
    time:
      ms: 86400000

