spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQLDialect
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  
  web:
    cors:
      allowed-origins: "http://localhost:3000,,https://yourdomain.com"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  graphql:
    schema:
      locations: classpath:graphql/

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          facebook:
            client-id: ${FB_CLIENT_ID}
            client-secret: ${FB_CLIENT_SECRET}
            scope: public_profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v14.0/dialog/oauth
            token-uri: https://graph.facebook.com/v14.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id

server:
  port: ${SERVER_PORT:8080}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:}
  api_key: ${CLOUDINARY_API_KEY:}
  api_secret: ${CLOUDINARY_API_SECRET:}

jwt:
  secret:
    key: SjkwTjN5aG41V2t6M0p4SllYNDlRYzJmQnU4cTgyMXFhU1hIUlJjS00=
  expiration:
    time:
      ms: 86400000

file:

momo:
  partnerCode: ${MOMO_PARTNER_CODE:MOMO}
  accessKey: ${MOMO_ACCESS_KEY}
  secretKey: ${MOMO_SECRET_KEY}
  endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api/create}
  returnUrl: ${MOMO_RETURN_URL:http://localhost:3000/payment/callback}
  ipnUrl: ${MOMO_IPN_URL:http://localhost:8080/api/payment/momo/ipn}
